Update openwrt-builder.yml

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -122,6 +122,13 @@ jobs:
         if [ -d openwrt/bin/targets ]; then
           echo "Target directory exists."
           cd openwrt/bin/targets/*/*
+          
+          # 确认切换目录成功
+          if [ $? -ne 0 ]; then
+            echo "Failed to change directory."
+            exit 1
+          fi
+
           rm -rf packages
           echo "FIRMWARE=$PWD" >> $GITHUB_ENV
           echo "status=success" >> $GITHUB_ENV
