Update openwrt-builder.yml

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -58,7 +58,13 @@ jobs:
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
         chmod +x $DIY_P1_SH
         cd openwrt
-        ./$DIY_P1_SH
+        # 检查 diy-part1.sh 是否存在
+        if [ -f "./$DIY_P1_SH" ]; then
+          ./$DIY_P1_SH
+        else
+          echo "Warning: $DIY_P1_SH not found!"
+          exit 1
+        fi
 
     - name: Update feeds
       run: cd openwrt && ./scripts/feeds update -a
@@ -72,7 +78,13 @@ jobs:
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
         chmod +x $DIY_P2_SH
         cd openwrt
-        ./$DIY_P2_SH
+        # 检查 diy-part2.sh 是否存在
+        if [ -f "./$DIY_P2_SH" ]; then
+          ./$DIY_P2_SH
+        else
+          echo "Warning: $DIY_P2_SH not found!"
+          exit 1
+        fi
 
     - name: Download package
       id: package
